Updates for PhysX4/5 split
o3de/RobotVacuumSample pull request #36
Opened 2024-02-01 23:40 UTC by spham-amzn

This updates the robot vacuum project to reference 'PhysX5' instead of 'PhysX' for simulation, now that both gems will be available at the same time (without the need of a cmake flag when creating the project from source). (Refer to https://github.com/o3de/o3de/pull/17436 ). Also updates need to match the development version of the ROS2 gem

2024-02-05 14:26 UTC, jhanca-robotecai requested changes
We should create a `development` branch and target all ongoing work over there before we make the `main` unusable. Unfortunately, I am not allowed to do it myself.

2024-02-05 17:06 UTC, spham-amzn commented
> We should create a `development` branch and target all ongoing work over there before we make the `main` unusable. Unfortunately, I am not allowed to do it myself.

I agree, created a development branch (now the default) and retargeted this PR.

2024-02-06 16:12 UTC, lumberyard-employee-dm approved these changes

2024-02-09 11:18 UTC, jhanca-robotecai approved these changes
Tested with the most recent o3de and o3de-extras as of now (39bbf9b73a and 2f9a8a71fa), with d09e050 cherry-picked from #33 and it works as expected.

I would suggest merging #33 first and this one right after.

2024-02-09 11:25 UTC, jhanca-robotecai commented
@spham-amzn 
one comment to our offline discussion: we tested the Python script to convert the prefabs and it worked as expected; the verbose information is also enough. The only thing that might cause the issues is AssetProcessor, which sometimes does not repreocess the prefabs automatically....

2024-02-09 13:09 UTC, michalpelka submitted a review, later dismissed

2024-02-09 13:09 UTC, michalpelka commented on project.json
> +        "ImGui",
I believe that :
ImGui, LandscapeCanvas, SaveData, ScriptCanvasPhysics, WhiteBox are not needed.

2024-02-09 13:11 UTC, michalpelka commented on project.json
> +        "ImGui",
I believe that :
ImGui, LandscapeCanvas, SaveData, ScriptCanvasPhysics, WhiteBox are not needed.

2024-02-09 21:54 UTC, merged